# Generated by Django 4.1.4 on 2022-12-20 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('ApplicationTime', models.DateTimeField(default=datetime.date.today)),
                ('ApplicationStatus', models.CharField(choices=[('Applied', 'Applied'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Interviewing', 'Interviewing')], default='Applied', max_length=100)),
                ('TermLength', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Summer', 'Summer')], max_length=100)),
                ('Pay', models.IntegerField(blank=True)),
                ('Position', models.CharField(max_length=100)),
            ],
        ),
    ]
