# Generated by Django 4.1.4 on 2022-12-20 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('Applied', models.DateField(default=datetime.date.today)),
                ('Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='input.application')),
            ],
            options={
                'ordering': ['Applied'],
            },
        ),
    ]
