# Generated by Django 4.1.4 on 2022-12-20 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_applicationinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationTime',
            field=models.DateTimeField(default=models.DateField(verbose_name=datetime.date(2022, 12, 20))),
        ),
    ]
