# Generated by Django 4.1.4 on 2022-12-20 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_alter_application_applicationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationTime',
            field=models.DateTimeField(default=datetime.date(2022, 12, 20)),
        ),
        migrations.AlterField(
            model_name='applicationinstance',
            name='Applied',
            field=models.DateField(default=datetime.date(2022, 12, 20)),
        ),
    ]
