# Generated by Django 4.1.4 on 2022-12-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_alter_application_applicationtime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationinstance',
            options={'ordering': ['Application']},
        ),
        migrations.RemoveField(
            model_name='application',
            name='ApplicationTime',
        ),
        migrations.RemoveField(
            model_name='applicationinstance',
            name='Applied',
        ),
    ]
