# Generated by Django 4.1.4 on 2022-12-20 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_alter_application_dayapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationStatus',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Interviewing', 'Interviewing')], default='Applied', max_length=100, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='CompanyName',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='DayApplied',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Day Applied'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Pay',
            field=models.IntegerField(blank=True, verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='application',
            name='TermLength',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Summer', 'Summer')], max_length=100, verbose_name='Term Length'),
        ),
    ]
