# Generated by Django 4.1.4 on 2022-12-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_applicationinstanceregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationInstanceRegister',
        ),
    ]
