# Generated by Django 4.1.4 on 2022-12-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0010_delete_applicationinstanceregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationInstance',
        ),
    ]
